#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing volume/shutdown listener...\n"
sudo cp pwr_vol_buttons.py /usr/local/bin/
sudo chmod +x /usr/local/bin/pwr_vol_buttons.py

echo "=> Starting volume/shutdown listener...\n"
sudo cp pwr_vol_buttons.sh /etc/init.d/
sudo chmod +x /etc/init.d/pwr_vol_buttons.sh

sudo update-rc.d pwr_vol_buttons.sh defaults
sudo /etc/init.d/pwr_vol_buttons.sh start

echo "Volume/shutdown listener installed.\n"
