#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping volume/shutdown listener...\n"
sudo update-rc.d pwr_vol_buttons.sh remove
sudo /etc/init.d/pwr_vol_buttons.sh stop

echo "=> Removing volume/shutdown listener...\n"
sudo rm -rf /usr/local/bin/pwr_vol_buttons.py 
sudo rm -rf /etc/init.d/pwr_vol_buttons.sh 

echo "Volume/shutdown listener uninstalled.\n"
